apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.service }}-virtual-service
  namespace: {{ .Release.Namespace }}
  labels:
    service: {{ .Values.service }}
  annotations:
    {{- range .Values.checkov_skips }}
    {{- . | toYaml | nindent 4 -}}
    {{- end }}
spec:
  hosts:
    - {{ .Values.host }}
  gateways:
    - {{.Values.service}}-egressgateway
  tls:
    - match:
        - gateways:
            - {{.Values.service}}-egressgateway
          port: {{ .Values.port }}
          sniHosts:
            - {{ .Values.host }}
      route:
        - destination:
            host: {{ .Values.host }}
            port:
              number: {{ .Values.port }}
          weight: 100
